"""Add game_user Association Table

Revision ID: 576948accbc6
Revises: f5b10defada4
Create Date: 2023-05-31 21:47:05.894235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576948accbc6'
down_revision = 'f5b10defada4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
