"""Add game_user Association Table

Revision ID: 6a0cc32f9210
Revises: 32774df4167a
Create Date: 2023-05-31 21:13:33.704195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0cc32f9210'
down_revision = '32774df4167a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
